### ISSUE TITLE
Requirements for GadgetReader

### ISSUE THREAD

**Issue by hansharhoff** [sbird/GadgetReader#3] opened 2015-04-14 10:10 UTC
I have tried to run make on your code.
However I get a long list of undefined references to various HDF5 functions.
Which libraries are required for compiling GadgetReader. Are any specific.
I am running Ubuntu. I believe I require the libhdf5-7 and libhdf5-dev packages.
Am I missing some packages?

Regards Hans

**Comment by sbird** [comment] 2015-04-14 15:26
Hi Hans,

Interesting, those two packages should be exactly the requirements. You need to have /usr/lib/x86_64-linux-gnu/libhdf5.so and /usr/lib/x86_64-linux-gnu/libhdf5_hl.so to compile Convert2HDF5. Could you please post the exact error message from make?

If you just want the code to work, HDF5 support is at the moment only needed for the (slightly experimental) support for converting a Gadget format snapshot to HDF5 format. If you don't want to do that you can change line 26 of the Makefile from:
OPTS = -DHAVE_HDF5
to
OPTS = 

But if you are willing I would like to work out why HDF5 doesn't work for you.

Thanks,
Simeon

**Comment by hansharhoff** [comment] 2015-04-14 16:39
Thanks,
your answer got me to the solution. The problem was that I hadn't done a
```make clean```
since installing the hdf5 packages.
It works now :)

May I suggest a note in the README file that lists the packages needed?
(and maybe suggest to run make clean for the bozos like me ;) )

Thank you for the quick reply and assistance.

**Comment by hansharhoff** [comment] 2015-04-14 16:43
Error message from running make with the HDF5 option:
hans@hans-VirtualBox:~/Sandbox/GadgetReader$ make clean
rm -f gadgetreader.o gadgetwriter.o PGIIhead PosDump btest librgad.so librgad.so.1 libwgad.so libwgad.so.1
hans@hans-VirtualBox:~/Sandbox/GadgetReader$ make
g++ -Wall -O2  -g -fPIC -DHAVE_HDF5   -c -o gadgetreader.o gadgetreader.cpp
gcc -shared -Wl,-soname,librgad.so.1 -o librgad.so.1  gadgetreader.o
ln -sf librgad.so.1 librgad.so
g++ -Wall -O2  -g -fPIC -DHAVE_HDF5   -c -o gadgetwriter.o gadgetwriter.cpp
gcc -shared -Wl,-soname,libwgad.so.1 -o libwgad.so.1 gadgetwriter.o
ln -sf libwgad.so.1 libwgad.so
g++ -Wall -O2  -g -fPIC -DHAVE_HDF5  -Wl,-rpath,/home/hans/Sandbox/GadgetReader -L/home/hans/Sandbox/GadgetReader -lrgad  PGIIhead.cpp librgad.so   -o PGIIhead
g++ -Wall -O2  -g -fPIC -DHAVE_HDF5  -Wl,-rpath,/home/hans/Sandbox/GadgetReader -L/home/hans/Sandbox/GadgetReader -lrgad  PosDump.cpp librgad.so   -o PosDump
g++ -Wall -O2  -g -fPIC -DHAVE_HDF5 Convert2HDF5.cpp -Wl,-rpath,/home/hans/Sandbox/GadgetReader -L/home/hans/Sandbox/GadgetReader -lrgad -lhdf5 -lhdf5_hl -lwgad -o Convert2HDF5
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Fcreate'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Sclose'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5T_NATIVE_LLONG_g'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5LTset_attribute_int'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Dopen2'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5T_NATIVE_FLOAT_g'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Dwrite'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Screate_simple'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5check_version'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Gcreate2'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Gopen2'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5LTset_attribute_double'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Dclose'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5LTset_attribute_uint'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Sselect_hyperslab'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Gclose'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5open'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Fopen'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Fclose'
/home/hans/Sandbox/GadgetReader/libwgad.so: undefined reference to `H5Dcreate2'
collect2: error: ld returned 1 exit status
make: *** [Convert2HDF5] Error 1

**Comment by sbird** [comment] 2015-04-14 17:59
Thanks for the information.

This occurs due to Ubuntu's use of the --as-needed option to ld by default. See: https://wiki.ubuntu.com/NattyNarwhal/ToolchainTransition#Indirect_Linking_for_Shared_Libraries

I can reproduce, so let me fix it. And, I'll add a comment to the README about libhdf5 as well, thanks for the reminder.

**Comment by sbird** [comment] 2015-04-14 18:13
This should be fixed by
https://github.com/sbird/GadgetReader/commit/b68b441906e438a61144de4182156dc0eeb95fe0
and the README is updated as well. Thanks

**Closed by sbird** 2015-04-14 18:13 UTC
